# Generated by Django 2.1.7 on 2019-02-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountingOfPersonalExpenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='categories',
            new_name='name',
        ),
    ]
