# Generated by Django 2.1.7 on 2019-02-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingOfPersonalExpenses', '0002_auto_20190214_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='dateD',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenses',
            name='dateM',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenses',
            name='dateY',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
