# Generated by Django 2.1.7 on 2019-02-26 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountingOfPersonalExpenses', '0003_auto_20190215_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='dateD',
            new_name='date_d',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='dateM',
            new_name='date_m',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='dateY',
            new_name='date_y',
        ),
    ]
